context:
  version: "0.0.23"

package:
  name: khiops-driver-gcs
  version: ${{ version }}

source:
  - url: https://github.com/KhiopsML/khiopsdriver-gcs/archive/refs/tags/${{ version }}.tar.gz
    sha256: 9d51ff7b298bd00b532d8b41b6e096ca07f1811493a3a5c8611bcd262de3f527
  - url: https://github.com/KhiopsML/khiopsdriver-shared/archive/ab7944134613199cd9112e5b6a6801c3257d5168.tar.gz
    sha256: 883482ba7f500130062fb0aa5fe955c2120ab5c9578cbb71c647fa11e6db9719
    target_directory: shared

build:
  number: 0

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake
    - ninja
  host:
    - fmt
    - spdlog
    - zlib
    - libgoogle-cloud-storage-devel <=2.37
    - libboost-devel
    - libboost-headers
    - libcrc32c
    - if: win
      then: libcurl

tests:
  - script:
      - if: unix
        then: test -f $PREFIX/lib/libkhiopsdriver_file_gcs${SHLIB_EXT}
        else:
          - if not exist %PREFIX%\Library\bin\libkhiopsdriver_file_gcs.dll exit 1

about:
  homepage: https://khiops.org
  license: BSD-3-Clause-Clear
  license_file: LICENSE
  summary: Khiops driver to access files on Google Cloud Storage
  description: The GCS driver plugin extends Khiops to enable processing of data files located on Google Cloud Storage

extra:
  recipe-maintainers:
    - popescu-v
    - sgouache
