context:
  version: "0.0.16"

package:
  name: khiops-driver-gcs
  version: ${{ version }}

source:
  - url: https://github.com/KhiopsML/khiopsdriver-gcs/archive/refs/tags/${{ version }}.tar.gz
    sha256: 5777f6a352c2c391005e85a8a0444f235c3c7583c781ca5491e1101116ca807d
  - url: https://github.com/KhiopsML/khiopsdriver-shared/archive/e010334b360b2ca1fc40de31f7d7b52cf4756581.tar.gz
    sha256: 7ac8fcef72769a268a68eeec78ae5831a727619ba009d3879bcb27545e9c7e2d
    target_directory: shared

build:
  number: 0

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake
    - ninja
  host:
    - fmt
    - spdlog
    - zlib
    - libgoogle-cloud-storage-devel<=2.37
    - libboost-devel
    - libboost-headers
    - libcrc32c
    - if: win
      then: libcurl

tests:
  - script:
    - if: unix
      then: test -f $PREFIX/lib/libkhiopsdriver_file_gcs${SHLIB_EXT}
      else: 
        - if not exist %PREFIX%\Library\bin\libkhiopsdriver_file_gcs.dll exit 1 

about:
  homepage: https://khiops.org
  license: BSD-3-Clause-Clear
  license_file: LICENSE
  summary: Khiops driver to access files on Google Cloud Storage
  description: The GCS driver plugin extends Khiops to enable processing of data files located on Google Cloud Storage

extra:
  recipe-maintainers:
    - popescu-v
    - sgouache
